// Generated by CoffeeScript 1.6.3
(function() {
  var App, AppController, Tobuy, TobuyController, app, router, _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Tobuy = (function(_super) {
    __extends(Tobuy, _super);

    function Tobuy() {
      _ref = Tobuy.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Tobuy.belongsTo('app', {
      inverseOf: 'all',
      as: function() {
        return App;
      }
    });

    Tobuy.property('title', {
      serialize: true
    });

    Tobuy.property('completed', {
      serialize: true
    });

    Tobuy.property('incomplete', {
      get: function() {
        return !this.completed;
      }
    });

    Tobuy.property('edit');

    Tobuy.prototype.remove = function() {
      return this.app.all["delete"](this);
    };

    return Tobuy;

  })(Serenade.Model);

  App = (function(_super) {
    __extends(App, _super);

    function App() {
      _ref1 = App.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    App.hasMany('all', {
      inverseOf: 'app',
      serialize: true,
      as: function() {
        return Tobuy;
      }
    });

    App.selection('active', {
      from: 'all',
      filter: 'incomplete'
    });

    App.selection('completed', {
      from: 'all',
      filter: 'completed'
    });

    App.property('label', {
      get: function() {
        if (this.activeCount === 1) {
          return 'item left';
        } else {
          return 'items left';
        }
      }
    });

    App.property('allCompleted', {
      get: function() {
        return this.activeCount === 0;
      },
      set: function(value) {
        var tobuy, _i, _len, _ref2, _results;
        _ref2 = this.all;
        _results = [];
        for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
          tobuy = _ref2[_i];
          _results.push(tobuy.completed = value);
        }
        return _results;
      }
    });

    App.property('newTitle');

    App.property('filter', {
      value: 'all'
    });

    App.property('filtered', {
      get: function() {
        return this[this.filter];
      }
    });

    App.property('filterAll', {
      get: function() {
        return this.filter === 'all';
      }
    });

    App.property('filterActive', {
      get: function() {
        return this.filter === 'active';
      }
    });

    App.property('filterCompleted', {
      get: function() {
        return this.filter === 'completed';
      }
    });

    return App;

  })(Serenade.Model);

  AppController = (function() {
    function AppController(app) {
      this.app = app;
    }

    AppController.prototype.newTobuy = function() {
      var title;
      title = this.app.newTitle.trim();
      if (title) {
        this.app.all.push({
          title: title
        });
      }
      return this.app.newTitle = '';
    };

    AppController.prototype.clearCompleted = function() {
      return this.app.all = this.app.active;
    };

    return AppController;

  })();

  TobuyController = (function() {
    function TobuyController(tobuy) {
      this.tobuy = tobuy;
    }

    TobuyController.prototype.removeTobuy = function() {
      return this.tobuy.remove();
    };

    TobuyController.prototype.edit = function() {
      this.tobuy.edit = true;
      return this.field.select();
    };

    TobuyController.prototype.edited = function() {
      if (this.tobuy.title.trim()) {
        this.tobuy.title = this.tobuy.title.trim();
        if (this.tobuy.edit) {
          this.tobuy.edit = false;
        }
      } else {
        this.tobuy.remove();
      }
      return this.tobuy.app.changed.trigger();
    };

    TobuyController.prototype.loadField = function(field) {
      this.field = field;
    };

    return TobuyController;

  })();

  app = new App(JSON.parse(localStorage.getItem('tobuys-serenade')));

  app.changed.bind(function() {
    return localStorage.setItem('tobuys-serenade', app);
  });

  router = Router({
    '/': function() {
      return app.filter = 'all';
    },
    '/active': function() {
      return app.filter = 'active';
    },
    '/completed': function() {
      return app.filter = 'completed';
    }
  });

  router.init();

  Serenade.view('app', document.getElementById('app').innerHTML);

  Serenade.view('tobuy', document.getElementById('tobuy').innerHTML);

  Serenade.controller('app', AppController);

  Serenade.controller('tobuy', TobuyController);

  document.body.insertBefore(Serenade.render('app', app), document.body.children[0]);

}).call(this);
